name: kostori
description: A anime app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.2+122
environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: 3.35.1

dependencies:
  antlr4: ^4.13.2
  app_links: ^6.4.0
  #音乐视频进度条
  audio_video_progress_bar: ^2.0.2
  battery_plus: ^6.2.3
  collection: ^1.19.0
  cookie_jar: any
  crypto: ^3.0.6
  desktop_webview_window:
    git:
      url: https://github.com/axlmly/flutter_desktop_webview
      path: packages/desktop_webview_window
      ref: 7801fc582ecf5a7351632887891ecf309a7b2583
  dio: ^5.9.0
  dlna_dart: ^0.1.0
  dynamic_color: ^1.8.1
  file_selector: ^1.0.3
  fl_chart: ^1.0.0
  flex_seed_scheme: ^3.5.1
  flex_color_picker: ^3.7.1
  flutter:
    sdk: flutter
  flutter_absolute_path_provider: ^0.0.1
  flutter_colorpicker: ^1.1.0
  flutter_displaymode: ^0.6.0
  flutter_file_dialog: ^3.0.2
  flutter_inappwebview:
    git:
      url: https://github.com/axlmly/flutter_inappwebview
      path: flutter_inappwebview
      ref: 3ef899b3db57c911b080979f1392253b835f98ab
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_memory_info: ^0.0.1
  flutter_mobx: ^2.2.1+1
  flutter_modular: ^6.4.1
  flutter_qjs:
    git:
      url: https://github.com/axlmly/flutter_qjs
      ref: 8feae95df7fb00455df129ad7a0dfec1d0e8d8e4
  flutter_rating_bar: ^4.0.1
  flutter_reorderable_grid_view: ^5.4.0
  flutter_saf:
    git:
      url: https://github.com/kostori-app/flutter_saf
      ref: fe182cdf40e5fa6230f451bc1d643b860f610d13
  flutter_svg: ^2.2.0
  #音量
  flutter_volume_controller: ^1.3.2
  gif: ^2.3.0
  html: ^0.15.5
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.2.0
  intl: ^0.20.2
  local_auth: ^2.3.0
  lodepng_flutter:
    git:
      url: https://github.com/axlmly/lodepng_flutter
      ref: ac7d05dde32e8d728102a9ff66e6b55f05d94ba1
  #media_kit系视频组件
  media_kit: ^1.2.0
  media_kit_libs_video: ^1.0.6
  media_kit_video: ^1.3.0
  mime: ^2.0.0
  mobx: ^2.3.3+1
  msix: ^3.16.12
  package_info_plus: ^8.3.1
  path: ^1.9.0
  path_provider: any
  permission_handler: ^12.0.1
  photo_view:
    git:
      url: https://github.com/axlmly/photo_view
      ref: a1255d1b5945aad4b7323303ec2ecdf0c90ffc4c
  pointycastle: ^4.0.0
  rhttp:
    git:
      url: https://github.com/kostori-app/rhttp
      ref: 4e5decf60db16a1ba4a957182ad6378ecc51802d
      path: rhttp
  #屏幕亮度
  screen_brightness_platform_interface: any
  scrollable_positioned_list:
    git:
      url: https://github.com/axlmly/flutter.widgets
      ref: 09e756b1f1b04e6298318d99ec20a787fb360f59
      path: packages/scrollable_positioned_list
  scrollview_observer: ^1.22.0
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.11
  shimmer_animation: ^2.1.0
  skeletonizer: ^2.1.0+1
  sliver_tools: ^0.2.12
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.39
  syntax_highlight: ^0.4.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  wakelock_plus: 1.3.2
  webdav_client:
    git:
      url: https://github.com/axlmly/webdav_client
      ref: 2f669c98fb81cff1c64fee93466a1475c77e4273
  window_manager: ^0.5.1
  yaml: any
  zip_flutter: ^0.0.12
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  animated_text_kit: ^4.2.3
  marquee: ^2.3.0
  flutter_downloader: ^1.12.0
  device_info_plus: ^11.5.0
  floating: ^6.0.0
  markdown_widget: ^2.3.2+8

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: images/app_icon.png
  image_path_android: images/app_icon.png
  image_path_ios: images/app_icon.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: images/app_icon.png
  adaptive_icon_monochrome: images/app_icon.png
  #  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: images/app_icon.png
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: images/app_icon.png

msix_config:
  display_name: Kostori
  execution_alias: kostori
  publisher: CN=阿修罗米莉亚, C=CN
  #  publisher: CN=SignPath Foundation, O=SignPath Foundation, L=Lewes, S=Delaware, C=US
  logo_path: images\app_icon.ico
  capabilities: internetClient, anime
  languages: en-us, zh-cn, zh-tw
  sign_msix: true
  install_certificate: false
  build_windows: false
  trim_logo: true
  store: false
  publisher_display_name: AXLMLY
  identity_name: com.axlmly.kostori
  #  msix_version: 1.1.8.0
  #  output_name: kostori-1.1.8.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/shaders/
    - assets/img/
    - assets/translation.json
    - assets/
