name: kostori
description: A anime app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.5+115
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: 3.29.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  #屏幕亮度
  screen_brightness_platform_interface: any
  #音量
  flutter_volume_controller: ^1.3.2
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.9
  #  flutter_colorpicker: ^1.0.0
  crypto: ^3.0.6
  pointycastle: ^4.0.0
  #应用图标
  flutter_launcher_icons: ^0.14.1
  #  provider: ^6.0.0
  get: ^4.6.6
  #音乐视频进度条
  audio_video_progress_bar: ^2.0.2
  #media_kit系视频组件
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6
  #  flutter_modular: ^6.3.3
  #暂时没懂,先留着
  mobx: ^2.3.3+1
  flutter_mobx: ^2.2.1+1
  uuid: ^4.5.1
  photo_view:
    git:
      url: https://github.com/wgh136/photo_view
      ref: 94724a0b
  url_launcher: ^6.3.0
  path_provider: any
  file_selector: ^1.0.3
  image_picker: ^1.0.2
  flutter_file_dialog: ^3.0.2
  package_info_plus: ^8.3.0
  html: ^0.15.5
  shimmer_animation: ^2.1.0
  cookie_jar: any
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_displaymode: ^0.6.0
  app_links: ^6.4.0
  flutter_reorderable_grid_view: ^5.4.0
  webdav_client:
    git:
      url: https://github.com/wgh136/webdav_client
      ref: 2f669c98fb81cff1c64fee93466a1475c77e4273
  sqlite3: ^2.7.4
  sqlite3_flutter_libs: ^0.5.30
  zip_flutter: ^0.0.12
  fl_chart: ^0.70.2
  collection: ^1.19.0
  window_manager: ^0.4.3
  flutter_inappwebview:
    git:
      url: https://github.com/venera-app/flutter_inappwebview
      path: flutter_inappwebview
      ref: 3ef899b3db57c911b080979f1392253b835f98ab
  flutter_qjs:
    git:
      url: https://github.com/wgh136/flutter_qjs
      ref: 8feae95df7fb00455df129ad7a0dfec1d0e8d8e4
  sliver_tools: ^0.2.12
  mime: ^2.0.0
  share_plus: ^10.1.4
  scrollable_positioned_list:
    git:
      url: https://github.com/venera-app/flutter.widgets
      ref: 09e756b1f1b04e6298318d99ec20a787fb360f59
      path: packages/scrollable_positioned_list
  desktop_webview_window:
    git:
      url: https://github.com/wgh136/flutter_desktop_webview
      path: packages/desktop_webview_window
      ref: 7801fc582ecf5a7351632887891ecf309a7b2583
  msix: ^3.16.8
  lodepng_flutter:
    git:
      url: https://github.com/venera-app/lodepng_flutter
      ref: ac7d05dde32e8d728102a9ff66e6b55f05d94ba1
  rhttp: ^0.11.1
  path: ^1.9.0
  battery_plus: ^6.2.0
  scrollview_observer: ^1.22.0
  flutter_modular: ^6.3.4
  local_auth: ^2.3.0
  yaml: any
  image_gallery_saver_plus: ^4.0.1
  flutter_saf:
    git:
      url: https://github.com/pkuislm/flutter_saf.git
      ref: fe182cdf40e5fa6230f451bc1d643b860f610d13
  dynamic_color: ^1.7.0
  flutter_memory_info: ^0.0.1
  syntax_highlight: ^0.4.0
  text_scroll: ^0.2.0
  flutter_rating_bar: ^4.0.1
  flex_seed_scheme: ^3.5.0
  antlr4: ^4.13.2
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.3
  flutter_svg: ^2.1.0
  dlna_dart: ^0.0.8
  gif: ^2.3.0
  flutter_absolute_path_provider: ^0.0.1
  wakelock_plus: 1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1
  hive_generator: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: images/app_icon.png
  image_path_android: images/app_icon.png
  image_path_ios: images/app_icon.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: images/app_icon.png
  adaptive_icon_monochrome: images/app_icon.png
  #  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: images/app_icon.png
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: images/app_icon.png

msix_config:
  display_name: Kostori
  publisher_display_name: AXLMLY
  identity_name: com.axlmly.kostori
  msix_version: 0.0.0.1
  trim_logo: false
  store: false
  logo_path: D:\kostori\assets\img\app_icon.png
  capabilities: internetClient, anime
  languages: en-us, zh-cn, zh-tw
  execution_alias: kostori
  publisher: CN=阿修罗米莉亚, C=CN
  output_path: D:\kostori\build\windows
  output_name: kostori-0.0.0.1


flutter:

  uses-material-design: true

  assets:
    - images/app_icon.png
    - images/avatar.png
    - images/avatar_small.png
    - images/github.png
    - images/
    - assets/shaders/
    - assets/img/
    - assets/translation.json
    - assets/
