// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'settings.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_SettingsData _$SettingsDataFromJson(
  Map<String, dynamic> json,
) => _SettingsData(
  animeDisplayMode: json['animeDisplayMode'] as String? ?? 'brief',
  animeTileScale: (json['animeTileScale'] as num?)?.toDouble() ?? 1.00,
  color: json['color'] as String? ?? 'blue',
  themeMode: json['themeMode'] as String? ?? 'system',
  newFavoriteAddTo: json['newFavoriteAddTo'] as String? ?? 'end',
  moveFavoriteAfterRead: json['moveFavoriteAfterRead'] as String? ?? 'none',
  proxy: json['proxy'] as String? ?? 'system',
  categories: json['categories'] as List<dynamic>? ?? const [],
  favorites: json['favorites'] as List<dynamic>? ?? const [],
  searchSources:
      (json['searchSources'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList() ??
      const [],
  showFavoriteStatusOnTile: json['showFavoriteStatusOnTile'] as bool? ?? true,
  showHistoryStatusOnTile: json['showHistoryStatusOnTile'] as bool? ?? false,
  blockedWords: json['blockedWords'] as List<dynamic>? ?? const [],
  defaultSearchTarget: json['defaultSearchTarget'] as String?,
  enableTapToTurnPages: json['enableTapToTurnPages'] as bool? ?? true,
  enablePageAnimation: json['enablePageAnimation'] as bool? ?? true,
  language: json['language'] as String? ?? 'system',
  cacheSize: (json['cacheSize'] as num?)?.toInt() ?? 2048,
  downloadThreads: (json['downloadThreads'] as num?)?.toInt() ?? 5,
  enableLongPressToZoom: json['enableLongPressToZoom'] as bool? ?? true,
  checkUpdateOnStart: json['checkUpdateOnStart'] as bool? ?? false,
  limitImageWidth: json['limitImageWidth'] as bool? ?? true,
  webdav: json['webdav'] as List<dynamic>? ?? const [],
  dataVersion: (json['dataVersion'] as num?)?.toInt() ?? 0,
  quickFavorite: json['quickFavorite'] as String?,
  enableTurnPageByVolumeKey: json['enableTurnPageByVolumeKey'] as bool? ?? true,
  enableClockAndBatteryInfoInReader:
      json['enableClockAndBatteryInfoInReader'] as bool? ?? true,
  authorizationRequired: json['authorizationRequired'] as bool? ?? false,
  enableDnsOverrides: json['enableDnsOverrides'] as bool? ?? false,
  dnsOverrides:
      json['dnsOverrides'] as Map<String, dynamic>? ??
      const <String, dynamic>{},
  sni: json['sni'] as bool? ?? true,
  autoAddLanguageFilter: json['autoAddLanguageFilter'] as String? ?? 'none',
  bangumiDataVer: json['bangumiDataVer'] as String?,
  getBangumiAllEpInfoTime: json['getBangumiAllEpInfoTime'] as String?,
  animeSourceListUrl: json['animeSourceListUrl'] as String? ?? '',
  gitMirror: json['gitMirror'] as bool? ?? false,
  initialPage: json['initialPage'] as String? ?? '0',
  debugInfo: json['debugInfo'] as bool? ?? false,
  bangumiUserName: json['bangumiUserName'] as String? ?? '',
  favoritePageId: (json['favoritePageId'] as num?)?.toInt() ?? 0,
  amoled: json['amoled'] as bool? ?? false,
  dynamicColor: json['dynamicColor'] as bool? ?? false,
  enableNoProxyOverrides: json['enableNoProxyOverrides'] as bool? ?? true,
  noProxyOverrides:
      (json['noProxyOverrides'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList() ??
      const ['bgm', 'bangumi'],
  ignoreBadCertificate: json['ignoreBadCertificate'] as bool? ?? false,
  statsSelectors: json['statsSelectors'] as List<dynamic>? ?? const [],
  favoriteTypeWish: json['favoriteTypeWish'] as String? ?? 'none',
  favoriteTypeDoing: json['favoriteTypeDoing'] as String? ?? 'none',
  favoriteTypeCollect: json['favoriteTypeCollect'] as String? ?? 'none',
  favoriteTypeOnHold: json['favoriteTypeOnHold'] as String? ?? 'none',
  favoriteTypeDropped: json['favoriteTypeDropped'] as String? ?? 'none',
  animeListDisplayMode: json['animeListDisplayMode'] as String? ?? 'paging',
  androidVideoRenderer: json['androidVideoRenderer'] as String? ?? 'auto',
  haEnable: json['haEnable'] as bool? ?? true,
  hardwareDecoder: json['hardwareDecoder'] as String? ?? 'auto-safe',
  audioOutType: json['audioOutType'] as bool? ?? true,
  videoSynchronizationMode:
      json['videoSynchronizationMode'] as String? ?? 'audio',
  translationSource: json['translationSource'] as String? ?? 'bing',
  calendarFetchEpisodes: json['calendarFetchEpisodes'] as bool? ?? false,
  enableNetLog: json['enableNetLog'] as bool? ?? true,
  enableHubLog: json['enableHubLog'] as bool? ?? true,
  enableStatsLog: json['enableStatsLog'] as bool? ?? true,
  enableSourceLog: json['enableSourceLog'] as bool? ?? true,
  enablePlayerLog: json['enablePlayerLog'] as bool? ?? true,
  deeplKey: json['deeplKey'] as String? ?? '',
  exploreSourcesOrder:
      json['exploreSourcesOrder'] as List<dynamic>? ?? const [],
  tileTitleMarquee: json['tileTitleMarquee'] as bool? ?? false,
  m3u8AdFilterEnabled: json['m3u8AdFilterEnabled'] as bool? ?? false,
  lanAutoDiscovery: json['lanAutoDiscovery'] as bool? ?? true,
  explorePagesV2:
      json['explorePagesV2'] as Map<String, dynamic>? ??
      const <String, dynamic>{},
  getCalendarDataTime: json['getCalendarDataTime'] as String?,
  getBangumiDataTime: json['getBangumiDataTime'] as String?,
  enableSkipUpdate: json['enableSkipUpdate'] as bool? ?? true,
  exploreHorizontalLayout: json['exploreHorizontalLayout'] as bool? ?? false,
  userNickname: json['userNickname'] as String? ?? '',
);

Map<String, dynamic> _$SettingsDataToJson(_SettingsData instance) =>
    <String, dynamic>{
      'animeDisplayMode': instance.animeDisplayMode,
      'animeTileScale': instance.animeTileScale,
      'color': instance.color,
      'themeMode': instance.themeMode,
      'newFavoriteAddTo': instance.newFavoriteAddTo,
      'moveFavoriteAfterRead': instance.moveFavoriteAfterRead,
      'proxy': instance.proxy,
      'categories': instance.categories,
      'favorites': instance.favorites,
      'searchSources': instance.searchSources,
      'showFavoriteStatusOnTile': instance.showFavoriteStatusOnTile,
      'showHistoryStatusOnTile': instance.showHistoryStatusOnTile,
      'blockedWords': instance.blockedWords,
      'defaultSearchTarget': instance.defaultSearchTarget,
      'enableTapToTurnPages': instance.enableTapToTurnPages,
      'enablePageAnimation': instance.enablePageAnimation,
      'language': instance.language,
      'cacheSize': instance.cacheSize,
      'downloadThreads': instance.downloadThreads,
      'enableLongPressToZoom': instance.enableLongPressToZoom,
      'checkUpdateOnStart': instance.checkUpdateOnStart,
      'limitImageWidth': instance.limitImageWidth,
      'webdav': instance.webdav,
      'dataVersion': instance.dataVersion,
      'quickFavorite': instance.quickFavorite,
      'enableTurnPageByVolumeKey': instance.enableTurnPageByVolumeKey,
      'enableClockAndBatteryInfoInReader':
          instance.enableClockAndBatteryInfoInReader,
      'authorizationRequired': instance.authorizationRequired,
      'enableDnsOverrides': instance.enableDnsOverrides,
      'dnsOverrides': instance.dnsOverrides,
      'sni': instance.sni,
      'autoAddLanguageFilter': instance.autoAddLanguageFilter,
      'bangumiDataVer': instance.bangumiDataVer,
      'getBangumiAllEpInfoTime': instance.getBangumiAllEpInfoTime,
      'animeSourceListUrl': instance.animeSourceListUrl,
      'gitMirror': instance.gitMirror,
      'initialPage': instance.initialPage,
      'debugInfo': instance.debugInfo,
      'bangumiUserName': instance.bangumiUserName,
      'favoritePageId': instance.favoritePageId,
      'amoled': instance.amoled,
      'dynamicColor': instance.dynamicColor,
      'enableNoProxyOverrides': instance.enableNoProxyOverrides,
      'noProxyOverrides': instance.noProxyOverrides,
      'ignoreBadCertificate': instance.ignoreBadCertificate,
      'statsSelectors': instance.statsSelectors,
      'favoriteTypeWish': instance.favoriteTypeWish,
      'favoriteTypeDoing': instance.favoriteTypeDoing,
      'favoriteTypeCollect': instance.favoriteTypeCollect,
      'favoriteTypeOnHold': instance.favoriteTypeOnHold,
      'favoriteTypeDropped': instance.favoriteTypeDropped,
      'animeListDisplayMode': instance.animeListDisplayMode,
      'androidVideoRenderer': instance.androidVideoRenderer,
      'haEnable': instance.haEnable,
      'hardwareDecoder': instance.hardwareDecoder,
      'audioOutType': instance.audioOutType,
      'videoSynchronizationMode': instance.videoSynchronizationMode,
      'translationSource': instance.translationSource,
      'calendarFetchEpisodes': instance.calendarFetchEpisodes,
      'enableNetLog': instance.enableNetLog,
      'enableHubLog': instance.enableHubLog,
      'enableStatsLog': instance.enableStatsLog,
      'enableSourceLog': instance.enableSourceLog,
      'enablePlayerLog': instance.enablePlayerLog,
      'deeplKey': instance.deeplKey,
      'exploreSourcesOrder': instance.exploreSourcesOrder,
      'tileTitleMarquee': instance.tileTitleMarquee,
      'm3u8AdFilterEnabled': instance.m3u8AdFilterEnabled,
      'lanAutoDiscovery': instance.lanAutoDiscovery,
      'explorePagesV2': instance.explorePagesV2,
      'getCalendarDataTime': instance.getCalendarDataTime,
      'getBangumiDataTime': instance.getBangumiDataTime,
      'enableSkipUpdate': instance.enableSkipUpdate,
      'exploreHorizontalLayout': instance.exploreHorizontalLayout,
      'userNickname': instance.userNickname,
    };
