import 'package:freezed_annotation/freezed_annotation.dart';

part 'settings.freezed.dart';

part 'settings.g.dart';

@Freezed(makeCollectionsUnmodifiable: false)
abstract class SettingsData with _$SettingsData {
  const factory SettingsData({
    @Default('brief') String animeDisplayMode,
    @Default(1.00) double animeTileScale,
    @Default('blue') String color,
    @Default('system') String themeMode,
    @Default('end') String newFavoriteAddTo,
    @Default('none') String moveFavoriteAfterRead,
    @Default('system') String proxy,
    @Default([]) List<dynamic> categories,
    @Default([]) List<dynamic> favorites,
    @Default([]) List<String> searchSources,
    @Default(true) bool showFavoriteStatusOnTile,
    @Default(false) bool showHistoryStatusOnTile,
    @Default([]) List<dynamic> blockedWords,
    String? defaultSearchTarget,
    @Default(true) bool enableTapToTurnPages,
    @Default(true) bool enablePageAnimation,
    @Default('system') String language,
    @Default(2048) int cacheSize,
    @Default(true) bool enableLongPressToZoom,
    @Default(false) bool checkUpdateOnStart,
    @Default(true) bool limitImageWidth,
    @Default([]) List<dynamic> webdav,
    @Default(0) int dataVersion,
    String? quickFavorite,
    @Default(true) bool enableTurnPageByVolumeKey,
    @Default(true) bool enableClockAndBatteryInfoInReader,
    @Default(false) bool authorizationRequired,
    @Default(false) bool enableDnsOverrides,
    @Default(<String, dynamic>{}) Map<String, dynamic> dnsOverrides,
    @Default(true) bool sni,
    @Default('none') String autoAddLanguageFilter,
    String? bangumiDataVer,
    String? getBangumiAllEpInfoTime,
    @Default('') String animeSourceListUrl,
    @Default(false) bool gitMirror,
    @Default('0') String initialPage,
    @Default(false) bool debugInfo,
    @Default('') String bangumiUserName,
    @Default(0) int favoritePageId,
    @Default(false) bool amoled,
    @Default(false) bool dynamicColor,
    @Default(true) bool enableNoProxyOverrides,
    @Default(['bgm', 'bangumi']) List<String> noProxyOverrides,
    @Default(false) bool ignoreBadCertificate,
    @Default([]) List<dynamic> statsSelectors,
    @Default('none') String favoriteTypeWish,
    @Default('none') String favoriteTypeDoing,
    @Default('none') String favoriteTypeCollect,
    @Default('none') String favoriteTypeOnHold,
    @Default('none') String favoriteTypeDropped,
    @Default('paging') String animeListDisplayMode,
    @Default('auto') String androidVideoRenderer,
    @Default(true) bool haEnable,
    @Default('auto-safe') String hardwareDecoder,
    @Default(true) bool audioOutType,
    @Default('audio') String videoSynchronizationMode,
    @Default('bing') String translationSource,
    @Default(false) bool calendarFetchEpisodes,
    @Default(true) bool enableNetLog,
    @Default(true) bool enableHubLog,
    @Default(true) bool enableStatsLog,
    @Default(true) bool enableSourceLog,
    @Default(true) bool enablePlayerLog,
    @Default('') String deeplKey,
    @Default([]) List<dynamic> exploreSourcesOrder,
    @Default(false) bool tileTitleMarquee,
    @Default(false) bool m3u8AdFilterEnabled,
    @Default(true) bool lanAutoDiscovery,
    @Default(<String, dynamic>{}) Map<String, dynamic> explorePagesV2,
    String? getCalendarDataTime,
    String? getBangumiDataTime,
    @Default(true) bool enableSkipUpdate,
    @Default(false) bool exploreHorizontalLayout,
    @Default('') String userNickname,
  }) = _SettingsData;

  factory SettingsData.fromJson(Map<String, dynamic> json) =>
      _$SettingsDataFromJson(json);
}
