import 'package:flutter/material.dart';
import 'package:kostori/foundation/app.dart';
import 'package:pretty_qr_code/pretty_qr_code.dart';

/// 统一风格的二维码：渐变模块 + 嵌入应用 logo。
/// 供分享卡片、局域网连接、协议分享等所有二维码场景复用。
class KostoriQrCode extends StatelessWidget {
  const KostoriQrCode({
    super.key,
    required this.content,
    this.size = 220,
    this.background = Colors.white,
    this.logoScale = 0.3,
  });

  final String content;

  final double size;

  /// 二维码背景色（二维码模块与背景的分界）
  final Color background;

  /// 嵌入 logo 相对二维码的缩放比例
  final double logoScale;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: size,
      height: size,
      child: PrettyQrView.data(
        data: content,
        errorCorrectLevel: QrErrorCorrectLevel.H,
        decoration: PrettyQrDecoration(
          background: background,
          shape: const PrettyQrSmoothSymbol(
            color: PrettyQrBrush.gradient(
              gradient: LinearGradient(
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
                colors: [Color(0xFF80D8DA), Color(0xFFF1919B)],
              ),
            ),
            roundFactor: 1.0,
          ),
          image: PrettyQrDecorationImage(
            image: const AssetImage('images/app_logo.png'),
            scale: logoScale,
            position: PrettyQrDecorationImagePosition.embedded,
          ),
        ),
      ),
    );
  }
}

/// 完整的二维码分享卡片：标题 + 二维码 + 副标题 + 水印。
/// 供分享弹层、二维码展示页等场景复用。
class KostoriQrCard extends StatelessWidget {
  const KostoriQrCard({
    super.key,
    required this.content,
    this.title,
    this.subtitle,
    this.showTitle = true,
    this.showSubtitle = true,
    this.qrBackground = Colors.white,
    this.qrSize = 220,
    this.showWatermark = true,
  });

  final String content;

  final String? title;

  final String? subtitle;

  final bool showTitle;

  final bool showSubtitle;

  final Color qrBackground;

  final double qrSize;

  final bool showWatermark;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          if (title != null && showTitle) ...[
            Text(
              title!,
              style: const TextStyle(
                color: Colors.white,
                fontSize: 20,
                fontWeight: FontWeight.w700,
                letterSpacing: 0.5,
                shadows: [
                  Shadow(blurRadius: 8, color: Colors.black45),
                ],
              ),
            ),
            const SizedBox(height: 12),
          ],
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: qrBackground,
              borderRadius: BorderRadius.circular(16),
              boxShadow: const [
                BoxShadow(
                  color: Colors.black26,
                  blurRadius: 20,
                  offset: Offset(0, 8),
                ),
              ],
            ),
            child: KostoriQrCode(
              content: content,
              size: qrSize,
              background: qrBackground,
            ),
          ),
          if (subtitle != null && showSubtitle) ...[
            const SizedBox(height: 10),
            Text(
              subtitle!,
              style: const TextStyle(
                color: Colors.white70,
                fontSize: 13,
                letterSpacing: 0.3,
              ),
              maxLines: 2,
              overflow: TextOverflow.ellipsis,
              textAlign: TextAlign.center,
            ),
          ],
          if (showWatermark) ...[
            const SizedBox(height: 8),
            Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(
                  Icons.auto_awesome,
                  size: 11,
                  color: Colors.grey.toOpacity(0.5),
                ),
                const SizedBox(width: 4),
                Text(
                  'Generated by Kostori v${App.version}',
                  style: TextStyle(
                    fontSize: 12,
                    color: Colors.grey.toOpacity(0.6),
                    letterSpacing: 0.3,
                  ),
                ),
              ],
            ),
          ],
        ],
      ),
    );
  }
}
