import 'package:flutter/material.dart';
import 'package:kostori/foundation/app.dart';
import 'package:kostori/i18n/strings.g.dart';

/// 统一的截图/分享图水印：图标 + 本地化的 “Generated by Kostori v{version}”。
/// 所有生成图片的底部署名都应使用它，避免各页面样式/文案不一致。
class KostoriWatermark extends StatelessWidget {
  const KostoriWatermark({super.key, this.color, this.fontSize = 12});

  final Color? color;
  final double fontSize;

  @override
  Widget build(BuildContext context) {
    final c = color ?? Colors.grey.withValues(alpha: 0.6);
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Icon(Icons.auto_awesome, size: fontSize - 1, color: c),
        const SizedBox(width: 5),
        Text(
          t.generatedBy(version: App.version),
          style: TextStyle(fontSize: fontSize, color: c, letterSpacing: 0.3),
        ),
      ],
    );
  }
}
