name: Build ALL
run-name: Build ALL
on:
  workflow_dispatch: { }
  release:
    types: [ published ]

jobs:
  Build_Android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64
      - name: Decode and install certificate
        env:
          STORE_FILE: ${{ secrets.ANDROID_KEYSTORE }}
          PROPERTY_FILE: ${{ secrets.ANDROID_KEY_PROPERTIES }}
        run: |
          echo "$STORE_FILE" | base64 --decode > android/app/keystore.jks
          echo "$PROPERTY_FILE" > android/key.properties
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Check rust-toolchain.toml
        run: rustup show
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: apks
          path: build/app/outputs/apk/release

  Build_Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install yq -y
          pip install httpx

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64

      - uses: dart-lang/setup-dart@v1

      - name: Activate msix
        run: dart pub global activate msix

      - name: Enable Git longpaths
        run: git config --system core.longpaths true

      - name: Flutter build windows
        run: |
          flutter pub get
          flutter build windows

      # === 构建未签名 zip/exe 安装包 ===
      - name: Build Installer or Zip (exe/zip)
        run: python windows/build.py

      # === 上传未签名 zip（供签名用）===
      - name: Upload unsigned zip artifact
        uses: actions/upload-artifact@v4
        id: unsigned-windows-zip-artifacts
        with:
          name: windows_unsigned_zip
          path: build/windows/Kostori-*.zip

      # === SignPath 签名 zip ===
      - run: New-Item -Path "build/windows/zip_signed_output" -ItemType Directory
      - name: Sign windows zip
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: 'fa047255-4772-4be1-b14f-5cfa62635877'
          project-slug: 'Kazumi'
          signing-policy-slug: 'release-signing'
          artifact-configuration-slug: 'Packet'
          github-artifact-id: '${{ steps.unsigned-windows-zip-artifacts.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'build/windows/zip_signed_output'

      - name: Upload signed zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_zip_signed_outputs
          path: build/windows/zip_signed_output/*.zip

      # === 解压签名后的 zip 替换 Release 用于构建 .msix ===
      - name: Replace Unpacked Artifact with Signed Artifact
        run: |
          $tag = "${{ github.ref_name }}"
          Expand-Archive -Path "build/windows/zip_signed_output/Kostori_windows_${tag}.zip" -DestinationPath "build/windows/x64/runner/Release" -Force

      # === 构建未签名 .msix ===
      - name: Build unsigned msix
        run: dart run msix:create

      - name: Upload unsigned msix artifact
        uses: actions/upload-artifact@v4
        id: unsigned-windows-msix-artifacts
        with:
          name: windows_msix_outputs
          path: build/windows/x64/runner/Release/*.msix

      # === SignPath 签名 .msix ===
      - run: New-Item -Path "build/windows/msix_signed_output" -ItemType Directory
      - name: Sign windows msix
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: 'fa047255-4772-4be1-b14f-5cfa62635877'
          project-slug: 'Kazumi'
          signing-policy-slug: 'release-signing'
          artifact-configuration-slug: 'MSIX'
          github-artifact-id: '${{ steps.unsigned-windows-msix-artifacts.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'build/windows/msix_signed_output'

      - name: Upload signed msix artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_msix_signed_outputs
          path: build/windows/msix_signed_output/*.msix

  Release:
    runs-on: ubuntu-22.04
    needs: [ Build_Android, Build_Windows ]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: apks
          path: outputs
      - uses: actions/download-artifact@v4
        with:
          name: windows_build
          path: outputs
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            outputs/*.apk
            outputs/*.zip
            outputs/*.exe
            outputs/*.msix
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
