name: Build ALL
run-name: Build ALL
on:
  workflow_dispatch: { }
  release:
    types: [ published ]

jobs:
  #Android
  Build_Android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64
      - name: Decode and install certificate
        env:
          STORE_FILE: ${{ secrets.ANDROID_KEYSTORE }}
          PROPERTY_FILE: ${{ secrets.ANDROID_KEY_PROPERTIES }}
        run: |
          echo "$STORE_FILE" | base64 --decode > android/app/keystore.jks
          echo "$PROPERTY_FILE" > android/key.properties
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Check rust-toolchain.toml
        run: rustup show
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: apks
          path: build/app/outputs/apk/release

  #windows
  Build_Windows:
    runs-on: "windows-latest"
    permissions: write-all

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Get tag name and set as environment variable # 添加此步骤以获取 tag
        run: |
          $tag = "${{ github.ref }}".Replace('refs/tags/', '')
          echo "tag=$(echo $tag)" >> $env:GITHUB_ENV

      - run: echo "Kostori-windows-${{ env.tag }}.zip build progress" # 更新这里的输出信息
      - run: choco install yq
      - name: Enable Git longpaths
        run: git config --system core.longpaths true
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: flutter pub get
      - run: flutter build windows

      - name: Compress and Rename Windows Zip
        run: Compress-Archive build/windows/x64/runner/Release/* Kostori-windows-${{ env.tag }}.zip

      - name: Upload windows zip outputs
        uses: actions/upload-artifact@v4
        with:
          name: Kostori_windows_zip
          path: |
            Kostori-windows-*.zip

      # Build MSIX
      - name: Build msix
        run: dart run msix:create

      - name: Move and Rename Windows MSIX
        run: mv build/windows/x64/runner/Release/kostori.msix Kostori-windows-${{ env.tag }}.msix

      - name: Upload windows msix outputs
        uses: actions/upload-artifact@v4
        with:
          name: Kostori_windows_msix
          path: |
            Kostori-windows-*.msix

  Release:
    runs-on: ubuntu-22.04
    needs: [ Build_Android, Build_Windows ]
    if: github.event_name == 'release'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: apks
          path: outputs

      - name: Download Windows Zip
        uses: actions/download-artifact@v4
        with:
          name: Kostori_windows_zip
          path: outputs

      - name: Download Windows MSIX
        uses: actions/download-artifact@v4
        with:
          name: Kostori_windows_msix
          path: outputs

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            outputs/*.apk
            outputs/Kostori-windows-*.zip
            outputs/Kostori-windows-*.msix
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
