name: Build ALL
run-name: Build ALL
on:
  workflow_dispatch: { }
  release:
    types: [ published ]

jobs:
  Build_Android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64
      - name: Decode and install certificate
        env:
          STORE_FILE: ${{ secrets.ANDROID_KEYSTORE }}
          PROPERTY_FILE: ${{ secrets.ANDROID_KEY_PROPERTIES }}
        run: |
          echo "$STORE_FILE" | base64 --decode > android/app/keystore.jks
          echo "$PROPERTY_FILE" > android/key.properties
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Check rust-toolchain.toml
        run: rustup show
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: apks
          path: build/app/outputs/apk/release

  #windows
  Build_Windows:
    name: "Release for Windows"
    runs-on: "windows-latest"
    permissions: write-all

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - run: |
          $tag = "${{ github.ref }}".Replace('refs/tags/', '')
          echo "tag=$(echo $tag)" >> $env:GITHUB_ENV
      - run: echo "Kostori_windows_${env:tag}.zip build progress"
      - run: choco install yq
      - name: Enable Git longpaths
        run: git config --system core.longpaths true
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: flutter pub get
      - run: flutter build windows
      - run: Compress-Archive build/windows/x64/runner/Release/* Kostori_windows_${env:tag}.zip
      - name: Upload windows outputs (unsigned zip)
        uses: actions/upload-artifact@v4
        id: unsigned-windows-zip-artifacts
        with:
          name: windows_outputs_unsigned_zip
          path: Kostori_windows_*.zip
      - run: New-Item -Path "build/windows/zip_signed_output" -ItemType Directory
      - name: Sign windows zip (Direct PowerShell)
        env:
          SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
        run: |
          $unsignedZipPath = "Kostori_windows_${env:tag}.zip"
          $signedZipOutputPath = "build/windows/zip_signed_output/Kostori_windows_${env:tag}_signed.zip"
          Submit-SigningRequest `
            -InputArtifactPath "$unsignedZipPath" `
            -ApiToken "$env:SIGNPATH_API_TOKEN" `
            -OrganizationId "ef5813e3-663f-4988-932d-7347304db90b" `
            -ProjectSlug "Kostori" `
            -SigningPolicySlug "kostori" `
            -OutputArtifactPath "$signedZipOutputPath" `
            -WaitForCompletion
        timeout-minutes: 15
      - name: Upload windows zip signed outputs
        uses: actions/upload-artifact@v4
        id: signed-windows-zip-artifacts
        with:
          name: windows_zip_signed_outputs
          path: build/windows/zip_signed_output/*.zip
      - name: Replace Unpacked Artifact with Signed Artifact
        run: Expand-Archive -Path "build/windows/zip_signed_output/Kostori_windows_${env:tag}_signed.zip" -DestinationPath "build/windows/x64/runner/Release" -Force
      - name: Build unsigned msix
        run: dart run msix:create
      - name: Upload windows msix outputs (unsigned)
        uses: actions/upload-artifact@v4
        id: unsigned-windows-msix-artifacts
        with:
          name: windows_msix_outputs_unsigned
          path: build/windows/x64/runner/Release/*.msix
      - run: New-Item -Path "build/windows/msix_signed_output" -ItemType Directory
      - name: Sign windows msix (Direct PowerShell)
        env:
          SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
        run: |
          $unsignedMsixPath = (Get-ChildItem -Path "build/windows/x64/runner/Release" -Filter "*.msix").FullName
          $signedMsixOutputPath = "build/windows/msix_signed_output/kostori_signed.msix"
          Submit-SigningRequest `
            -InputArtifactPath "$unsignedMsixPath" `
            -ApiToken "$env:SIGNPATH_API_TOKEN" `
            -OrganizationId "ef5813e3-663f-4988-932d-7347304db90b" `
            -ProjectSlug "Kostori" `
            -SigningPolicySlug "kostori" `
            -OutputArtifactPath "$signedMsixOutputPath" `
            -WaitForCompletion
        timeout-minutes: 15
      - name: Upload windows msix signed outputs
        uses: actions/upload-artifact@v4
        id: signed-windows-msix-artifacts_final
        with:
          name: windows_msix_signed_outputs
          path: build/windows/msix_signed_output/*.msix

  Release:
    runs-on: ubuntu-22.04
    needs: [ Build_Android, Build_Windows ]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: apks
          path: outputs
      - name: Download windows zip build file
        uses: actions/download-artifact@v4
        with:
          name: windows_zip_signed_outputs
          path: windows_zip_signed_outputs
      - name: List files in windows_outputs directory
        run: ls -l windows_zip_signed_outputs
      - name: Copy windows build file to root
        run: cp windows_zip_signed_outputs/* Kostori_windows_${{ env.tag }}.zip

      - name: Download windows msix build file
        uses: actions/download-artifact@v4
        with:
          name: windows_msix_signed_outputs
          path: windows_msix_signed_outputs
      - name: List files in windows_msix_signed_outputs directory
        run: ls -l windows_msix_signed_outputs
      - name: Copy windows build file to root
        run: cp windows_msix_signed_outputs/* Kostori_windows_${{ env.tag }}.msix
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            outputs/*.apk
            Kostori_windows_*.zip
            Kostori_windows_*.msix
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
